-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRZSqfOsGQvseTh2s
jdxP+t5ddjuwmR1vOZw6QUbyjRWgCgYIKoZIzj0DAQehRANCAASbArJCoPJOgfM2
1ZzgYndIz/JszgISljsi7ydve+B2BhzSzYr1fTfBb8lDRO7R4Xy5R4bfIDapOQXg
8bamJD/4
-----END PRIVATE KEY-----